# Generated by Django 3.2.9 on 2021-11-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costelaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapio',
            name='resumo',
            field=models.TextField(help_text='Descrição do prato', max_length=1000),
        ),
    ]
