# Generated by Django 3.2.9 on 2021-11-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costelaria', '0002_alter_cardapio_resumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Sobremesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='prato',
            options={'ordering': ['nome']},
        ),
        migrations.RenameField(
            model_name='prato',
            old_name='first_name',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='cardapio',
            name='titulo',
        ),
        migrations.AddField(
            model_name='cardapio',
            name='bebida',
            field=models.ManyToManyField(help_text='Selecione a bebida', to='costelaria.Bebida'),
        ),
        migrations.AddField(
            model_name='cardapio',
            name='sobremesa',
            field=models.ManyToManyField(help_text='Selecione a sobremesa', to='costelaria.Sobremesa'),
        ),
    ]
