# Generated by Django 3.2.9 on 2021-11-07 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costelaria', '0003_auto_20211107_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardapio',
            name='bebida',
        ),
        migrations.RemoveField(
            model_name='cardapio',
            name='prato',
        ),
        migrations.RemoveField(
            model_name='cardapio',
            name='sobremesa',
        ),
        migrations.AlterModelOptions(
            name='prato',
            options={},
        ),
        migrations.DeleteModel(
            name='Bebida',
        ),
        migrations.DeleteModel(
            name='cardapio',
        ),
        migrations.DeleteModel(
            name='Sobremesa',
        ),
    ]
