# Generated by Django 3.2.9 on 2021-11-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costelaria', '0004_auto_20211107_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sobremesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bebida', models.ManyToManyField(help_text='Selecione a bebida', to='costelaria.Bebida')),
                ('prato', models.ManyToManyField(help_text='Selecione o prato', to='costelaria.Prato')),
                ('sobremesa', models.ManyToManyField(help_text='selecione a sobremesa', to='costelaria.Sobremesa')),
            ],
        ),
    ]
