# Generated by Django 3.2.9 on 2021-11-08 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costelaria', '0005_bebida_cardapio_sobremesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cardapio',
            name='mesa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='costelaria.mesa'),
        ),
    ]
