# Generated by Django 3.2.9 on 2021-11-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costelaria', '0006_auto_20211108_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa', models.CharField(help_text='Digite o número da mesa', max_length=100)),
                ('bebida', models.ManyToManyField(help_text='Selecione a bebida', to='costelaria.Bebida')),
                ('prato', models.ManyToManyField(help_text='Selecione o prato', to='costelaria.Prato')),
                ('sobremesa', models.ManyToManyField(help_text='selecione a sobremesa', to='costelaria.Sobremesa')),
            ],
        ),
        migrations.DeleteModel(
            name='Cardapio',
        ),
        migrations.DeleteModel(
            name='Mesa',
        ),
    ]
